# Generated by Django 5.0.6 on 2024-05-13 10:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0002_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="products"),
        ),
    ]
