# Generated by Django 5.0.6 on 2024-05-22 10:20

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("apps", "0006_rename_created_at_category_created_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="category",
            old_name="created",
            new_name="created_at",
        ),
        migrations.RenameField(
            model_name="product",
            old_name="created",
            new_name="created_at",
        ),
    ]
